In [69]:
import pandas as pd

In [70]:
import pandas as pd

file_path = "Microarray Data/Metadata/171125_1417.gal"

df = pd.read_csv(
    file_path,
    sep="\t",
)

In [71]:
df

      Block  Column  Row    ID  Name
0         4       1    1   1E3   NaN
1         4       2    1   1A5   NaN
2         4       3    1   1G5   NaN
3         4       4    1   1C1   NaN
4         4       5    1   1E1   NaN
...     ...     ...  ...   ...   ...
5179     30       8   15  1C11   NaN
5180     30       9   15  1E11   NaN
5181     30      10   15   1A7   NaN
5182     30      11   15   1G7   NaN
5183     30      12   15   1C9   NaN

[5184 rows x 5 columns]

In [72]:
platemap_df = pd.read_excel("Microarray Data/Metadata/Manhattan RecombiChip v2 platemap.xlsx", )

In [73]:
platemap_df

       ID Location in box
0     1A1            A-A1
1     1B1            A-A2
2     1C1            A-A3
3     1D1            A-A4
4     1E1            A-A5
..    ...             ...
103   1G9      BORD_PERT1
104  1A11         CAP_AB2
105  1C11      BORD_PERT2
106  1E11         BUFFER6
107  1G11         CAP_AB3

[108 rows x 2 columns]

In [74]:
merged_df = df.merge(
    platemap_df[['ID', 'Location in box']], 
    on='ID', 
    how='left'
)

In [75]:
merged_df = merged_df.drop('Name', axis = 1)

In [76]:
plate_id = pd.read_excel("Microarray Data/Metadata/Derek .xlsx")
plate_id.head()

,ID,Target,Short code,Location in microarray plate,Strain/Description,Code BEI,Target.1,Conc,Location in box,"Con in ug/ml (For lyophilised, mostly diluting to 500ug/ml)",Diluting to 200ug/ml then do a 1:1 dilution with printing buffer (top up to 100ul with printing buffer).Amount to take is shown below,Instructions for lysates and lyophilised targets,Amount of printing buffer to top up to 100ul,Amount in vial,First dilutions,Second batch printing (increasing amount of antigen so as to get better signal). Add from stock at 500ug/ml to microarray stock at 200ug/ml,Unnamed: 16
0,3,Hepatitis B Virus,HEPB.ADR,NaN,"Surface Antigen, Subtype adr (HBsAg/adr)",\tNR-3822,Antigen,NaN,A-A1,NaN,NaN,Take 20ul of the serum,80.0,NaN,DONE,Add 10 ul,NaN
1,196,Diptheria toxoid,DIP.TOX,NaN,Toxoid,Eric,NaN,0.5mg/ml,A-A2,500.0,40,NaN,60.0,100ug,DONE,NaN,NaN
2,203,Native Parainfluenza Virus type 2 protein,PARAINFV.2,NaN,ab274661,Abcam,Protein,3.6mg/ml,A-A3,3600.0,5.555556,NaN,95.0,NaN,DONE,Add 10 ul,NaN
3,201,Native Parainfluenza Virus type 3 protein,PARAINFV.3,NaN,ab274662,Abcam,Protein,4.9mg/ml,A-A4,4900.0,4.081633,NaN,95.0,NaN,DONE,Add 20 ul,NaN
4,202,Native Parainfluenza Virus type 1 protein,PARAINFV.1,NaN,ab274660,Abcam,Protein,2.5mg/ml,A-A5,2500.0,8,NaN,92.0,NaN,DONE,Add 10 ul,NaN

In [77]:
plate_id = plate_id.drop_duplicates(subset='Location in box')

In [78]:
merged_df = merged_df.merge(
    plate_id[['Location in box', 'Short code']],
    on='Location in box',
    how='left'   
)

In [79]:
merged_df

      Block  Column  Row    ID Location in box  Short code
0         4       1    1   1E3            A-E1    ANDESV.N
1         4       2    1   1A5            D-A2     RSVA2.G
2         4       3    1   1G5            D-A8     HSV2.GD
3         4       4    1   1C1            A-A3  PARAINFV.2
4         4       5    1   1E1            A-A5  PARAINFV.1
...     ...     ...  ...   ...             ...         ...
5179     30       8   15  1C11      BORD_PERT2         NaN
5180     30       9   15  1E11         BUFFER6         NaN
5181     30      10   15   1A7   STREP_PNEUMO2         NaN
5182     30      11   15   1G7        LAND_IGA         NaN
5183     30      12   15   1C9        LAND_IGG         NaN

[5184 rows x 6 columns]